canvas=document.getElementById("canvas1");
ctx=canvas.getContext("2d")
color="blue"
ctx.beginPath()
ctx.strokeStyle=color
ctx.lineWidth=2
ctx.arc(100,100,20,0,2*Math.PI)
ctx.stroke()
color="black"
ctx.beginPath()
ctx.strokeStyle=color
ctx.lineWidth=2
ctx.arc(150,100,20,0,2*Math.PI)
ctx.stroke()
color="red"
ctx.beginPath()
ctx.strokeStyle=color
ctx.lineWidth=2
ctx.arc(200,100,20,0,2*Math.PI)
ctx.stroke()
color="yellow"
ctx.beginPath()
ctx.strokeStyle=color
ctx.lineWidth=2
ctx.arc(125,125,20,0,2*Math.PI)
ctx.stroke()
color="black"
ctx.beginPath()
ctx.strokeStyle=color
ctx.lineWidth=2
ctx.arc(175,125,20,0,2*Math.PI)
ctx.stroke()
ctx.rect(75,75,150,75)
ctx.stroke()